[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fedprox"
version = "1.0.0"
description = "FedProx: Federated Optimization in Heterogeneous Networks"
license = "Apache-2.0"

dependencies = [
    "flwr[simulation]>=1.12.0,<2.0",
    "flwr-datasets[vision]>=0.3.0,<1.0",
    "torch>=2.2.1,<3.0",
    "torchvision>=0.17.1,<1.0",
]


[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "fedprox"

[tool.flwr.app.components]
serverapp = "fedge.server_app:app"
clientapp = "fedge.client_app:app"

[tool.flwr.app.config]
num-server-rounds = 150
fraction-fit = 0.5        
min_available_clients = 3  
# FedProx hyperparameters
proximal_mu = 0.01        
local-epochs = 1         
batch_size = 32           
# Data heterogeneity
dirichlet_alpha = 0.5     
seed = 0            

[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 10
options.ray_init_args.local_mode = true
options.ray_init_args.ignore_reinit_error = true
